version: "3.9"
services:
  open-notebook:
    image: ghcr.io/POWERFULMOVES/Pmoves-open-notebook:main
    restart: unless-stopped
    networks: [pmoves-net]
    ports:
      - "8503:8502"  # UI
      - "5056:5055"  # API
networks:
  pmoves-net:
    external: true

